/* Number of total columns/semesters: */
window.semesters = 12;

/* List of available colors to toggle a course as completed */
/* The first color is default for selecting options as well, so make sure to choose that one wisely */
window.colors = ["#b1fca4", "#fac6ff", "#a8c9ff"];

// Order of courses matters: do not swap positions. Append at the end.
window.courses = [
    {
        name: "Introdução à computação",
        credits: 4,
        code: "InCmp",
        semester: 1,
    },
    {
        name: "Int. a Eng. de Computação",
        credits: 2,
        code: "IEC",
        semester: 1,
    },
    {
        name: "Cálculo I",
        credits: 6,
        code: "C1A",
        semester: 1,
    },
    {
        name: "Química Geral B",
        credits: 4,
        code: "QGB",
        semester: 1,
        requirements: [4],
    },
    {
        name: "Química Geral Experimental",
        credits: 2,
        code: "QGE",
        semester: 1,
        requirements: [3],
    },
    {
        name: "Fundamentos de Lógica",
        credits: 2,
        code: "FL",
        semester: 1,
    },
    {
        name: "Programação Orientada a Objetos",
        credits: 4,
        code: "POO",
        semester: 2,
        requirements: [0],
    },
    {
        name: "Álgebra Linear",
        credits: 4,
        code: "AL",
        semester: 2,
    },
    {
        name: "CÁLCULO 2A",
        credits: 6,
        code: "C2A",
        semester: 2,
        requirements: [2],
    },
    {
        name: "FÍSICA I",
        credits: 4,
        code: "FIS I",
        semester: 2,
        requirements: [2],
    },
    {
        name: "Física II",
        credits: 2,
        code: "FEx I",
        semester: 2,
        requirements: [9],
    },
    {
        name: "ESTRUTURAS DE DADOS I",
        credits: 4,
        code: "ED1",
        semester: 3,
        requirements: [6],
    },
    {
        name: "EQ. DIFERENCIAIS ORDINÁRIAS",
        credits: 4,
        code: "EDO",
        semester: 3,
        requirements: [2, 6],
    },
    {
        name: "CÁLCULO 3A",
        credits: 4,
        code: "C3A",
        semester: 3,
        requirements: [8],
    },
    {
        name: "FÍSICA III",
        credits: 4,
        code: "FIS III",
        semester: 3,
        requirements: [8],
    },
    {
        name: "MATEMÁTICA DISCRETA",
        credits: 4,
        code: "MD",
        semester: 3,
    },
    {
        name: "ESTRUTURAS DE DADOS II ",
        credits: 4,
        code: "ED2",
        semester: 4,
        requirements: [11],
    },
    {
        name: "MÉT. MAT. LINEARES",
        credits: 4,
        code: "MML",
        semester: 4,
        requirements: [12],
    },
    {
        name: "ELETROMAGNE..",
        credits: 4,
        code: "ELM",
        semester: 4,
        requirements: [13, 19],
    },
    {
        name: "FÍSICA IV",
        credits: 4,
        code: "FIS IV",
        semester: 4,
        requirements: [18, 20],
    },
    {
        name: "FÍSICA EXPERIMENTAL IV",
        credits: 2,
        code: "FEx IV",
        semester: 4,
        requirements: [19],
    },
    {
        name: "DESENHO TÉCNICO",
        credits: 2,
        code: "DT",
        semester: 4,
    },
    {
        name: "BANCO DE DADOS",
        credits: 4,
        code: "BD",
        semester: 5,
        requirements: [16],
    },
    {
        name: "ANL. DE SIST. LINEARES ",
        credits: 4,
        code: "ASL",
        semester: 5,
        requirements: [17],
    },
    {
        name: "CIRCUITOS ELÉTRICOS 1",
        credits: 4,
        code: "CE1",
        semester: 5,
        requirements: [12, 14, 25],
    },
    {
        name: "LAB. DE CIRC. ELÉTRICOS 1",
        credits: 1,
        code: "LCE1",
        semester: 5,
        requirements: [24],
    },
    {
        name: "MATERIAIS ELÉTRICOS",
        credits: 4,
        code: "ME",
        semester: 5,
        requirements: [14, 27],
    },
    {
        name: "LAB. DE MAT. ELÉTRICOS",
        credits: 1,
        code: "LME",
        semester: 5,
        requirements: [26],
    },
    {
        name: "PROBABILIDADE E ESTATÍSTICA A",
        credits: 4,
        code: "PE.A",
        semester: 6,
    },
    {
        name: "SISTEMAS DE CONTROLE",
        credits: 4,
        code: "SC",
        semester: 6,
        requirements: [23],
    },
    {
        name: "CONV. ELETROMEC. DE E",
        credits: 4,
        code: "CEE1",
        semester: 6,
        requirements: [31, 18],
    },
    {
        name: "LAB. CONV. ELETROMEC. DE E1",
        credits: 1,
        code: "LCEE1",
        semester: 6,
        requirements: [30],
    },
    {
        name: "ELETRÔNICA 1",
        credits: 4,
        semester: 6,
        code: "ELE1",
        requirements: [18, 24, 26, 33],
    },
    {
        name: "LAB. DE ELETRÔNICA 1",
        credits: 4,
        code: "LELE1",
        semester: 6,
        requirements: [32],
    },
    {
        name: "FENÔMENOS DE TRANSPORTE",
        credits: 4,
        code: "FT",
        semester: 7,
        requirements: [12],
    },
    {
        name: "CÁLCULO NUMÉRICO",
        credits: 4,
        code: "CN",
        semester: 7,
        requirements: [0, 2, 7],
    },
    {
        name: "LAB. DE SIS. DE CONTROLE",
        credits: 1,
        code: "LSC",
        semester: 7,
        requirements: [29],
    },
    {
        name: "ESTÁTICA",
        credits: 4,
        code: "EST",
        semester: 7,
        requirements: [3],
    },
    {
        name: "LAB. DE CIRCUITOS LÓG. 1",
        credits: 1,
        code: "LCL1",
        semester: 7,
        requirements: [39],
    },
    {
        name: "CIRCUITOS LÓGICOS 1 ",
        credits: 4,
        code: "CL1",
        semester: 7,
        requirements: [38, 5],
    },
    {
        name: "SISTEMAS OPERACIONAIS",
        credits: 4,
        code: "SO",
        semester: 8,
        requirements: [6],
    },
    {
        name: "METODOLOGIA CIENTÍFICA",
        credits: 2,
        code: "MC",
        semester: 8,
    },
    {
        name: "RESIST. DOS MAT. I",
        credits: 4,
        code: "RM1",
        semester: 8,
        requirements: [37],
    },
    {
        name: "TEORIA DE TELECOMUNIC.",
        credits: 4,
        code: "TT",
        semester: 8,
        requirements: [23],
    },
    {
        name: "LAB. DE MICROPR. E MICROCONT.",
        credits: 1,
        code: "LMIC",
        semester: 8,
        requirements: [45],
    },
    {
        name: "MICROPROC. E MICROCONT.",
        credits: 4,
        code: "MIC",
        semester: 8,
        requirements: [32, 39, 44],
    },
    {
        name: "SISTEMAS DISTRIBUÍDOS 1",
        credits: 4,
        code: "SD1",
        semester: 9,
        requirements: [6],
    },
    {
        name: "1200h",
        credits: 1200,
        semester: 9,
        step: 1,
    },
    {
        name: "LINGUAGENS FORMAIS",
        credits: 2,
        code: "LF",
        semester: 9,
        requirements: [47],
    },
    {
        name: "DIREITO PARA ENGENHARIA",
        credits: 2,
        code: "DE",
        semester: 9,
        requirements: [47],
    },
    {
        name: "REDES DE COMPUTADORES 1",
        credits: 4,
        code: "RC1",
        semester: 9,
    },
    {
        name: "CIÊNCIAS DO AMBIENTE",
        credits: 4,
        code: "CA",
        semester: 9,
    },
    {
        name: "ARQUIT. DE COMPUTA. 1",
        credits: 4,
        code: "AC1",
        semester: 9,
        requirements: [45, 39],
    },
    {
        name: "COMPILADORES 1 ",
        credits: 4,
        code: "COM1",
        semester: 10,
        requirements: [48],
    },
    {
        name: "INTELIGÊNCIA COMPUTACIONAL",
        credits: 4,
        code: "IC",
        semester: 10,
        requirements: [16],
    },
    {
        name: "PESQUISA OPERACIONAL 1",
        credits: 4,
        code: "PO1",
        semester: 10,
        requirements: [35],
    },
    {
        name: "FUND. DA ADMINISTRAÇÃO",
        credits: 2,
        code: "FA",
        semester: 10,
    },
    {
        name: "ECONOMIA B",
        credits: 4,
        code: "ECO.B",
        semester: 10,
    },
    {
        name: "ENGENHARIA DE SOFTWARE 1",
        credits: 4,
        code: "ES1",
        semester: 10,
        requirements: [47],
    },
    {
        name: "COMPUTAÇÃO GRÁFICA",
        credits: 4,
        code: "COG",
        semester: 11,
        requirements: [6],
    },
    {
        name: "2400h",
        credits: 4,
        semester: 11,
        step: 1,
    },
    {
        name: "2144",
        credits: 4,
        semester: 11,
        step: 1,
    },
    {
        name: "PROJ. F. DE CURSO P/ ENG. COMP. 1",
        credits: 4,
        code: "PF1",
        semester: 11,
        requirements: [60],
    },
    {
        name: "ENGENHARIA ECONÔMICA ",
        credits: 4,
        code: "EE",
        semester: 11,
        requirements: [57],
    },
    {
        name: "PROJ. F. DE CURSO P/ ENG. COMP. 2",
        credits: 4,
        code: "PF2",
        semester: 12,
        requirements: [62],
    },
    {
        name: "ESTÁGIO SUPERVISIONADO ",
        credits: 320,
        code: "ES",
        semester: 12,
        requirements: [61],
    },
];
